### PR TITLE
Add max allowed core version if it's incorrect

### PR DESCRIPTION
**Pull request by forslund**
Set it to the current core version

### CODE REVIEW

**Comment by penrods** [comment]
Shall we also have it increase it?  E.g. if the setting is "18.2" and you are running on "18.4", then we can assume that the user is OK with at least 18.4

**Comment by forslund** [comment]
Ok, let me test that real quick

**Comment by forslund** [comment]
I updated the PR to update lower versions to current core version. Should update if
- Setting is missing
- Setting is of wrong type
- Setting is lower than the current version of core

**Comment by penrods** [comment]
Just noting that comparing using floats is only safe as long as we don't release in Oct, Nov or Dec.  (18+10/10 = 19.0 not 18.10).  But I don't think we'll be changing from 02/08 anytime soon, so not really worried.

**Review by penrods — APPROVED** [review]
LGTM

**Pull request merged**
